In [ ]:
import numpy as np

In [ ]:
#Задание №1
a = np.array([[1, 2, 1], [-2, 1, 1]])
b = np.array([[3, 1], [-1, 0], [2, 4]])
c = np.array([[-2, 1], [1, -1], [1, 2]])
result1 = 2*b     #матрицы a и b не суммируются т.к. они разных размеров
result2 = b + 2*c
print('Результат 1:\n', result1)
print('Результат 2:\n', result2)

Результат 1:
 [[ 6  2]
 [-2  0]
 [ 4  8]]
Результат 2:
 [[-1  3]
 [ 1 -2]
 [ 4  8]]


In [ ]:
#Задача №2
matrix = np.zeros((8, 8), dtype=np.int32) #выбрал разрядность 32, но только интуитивно. Есди будет возможность, объясните, пожалуйста в комментарии к заданию, верно это или нет; имеет это значение или нет
matrix[::2, ::2] = 1
matrix[1::2, 1::2] = 1
print(matrix)


[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [ ]:
#Задача №3
vecA = np.arange(0, 1.5, 0.1, dtype=np.float_)
vecB = np.arange(1, 7, dtype=np.int_)
vecA_to_matrix = vecA.reshape(5, 3)
vecB_to_matrix = vecB.reshape(3, 2)
mult_matrices = vecA_to_matrix @ vecB_to_matrix
print('Матрица А:\n', vecA_to_matrix)
print('Матрица В:\n', vecB_to_matrix)
print('Умножение:\n', mult_matrices)

Матрица А:
 [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
Матрица В:
 [[1 2]
 [3 4]
 [5 6]]
Умножение:
 [[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


In [ ]:
#Задача №4
vec = np.arange(1, 72, 2, dtype=np.int32)
result = vec[(vec % 3 == 0)]
print('Вектор:\n', vec)
print('Элементы, кратные 3:\n', result)

Вектор:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]
Элементы, кратные 3:
 [ 3  9 15 21 27 33 39 45 51 57 63 69]
